name: Deploy

on:
  push:
    branches: [main]
  pull-request:
    branches: [main]

  jobs: 
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install (root)
          run: npm install
        - name: Install (server)
          run: npm install --prefix server
        - name: Build (server)
          run: npm run build --prefix server
        - name: Insall (client)
          run: npm install --prefix client
        - name: Build (client)
          run: npm run build --prefix client
        - name: Test
          run: 
            npm install
            npm run test
        - name: Deploy
          if: github.ref == 'refs/heads/main'
          env: 
            DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL}}
            run: curl "$DEPLOY_URL"
